project:
  type: website
  output-dir: _site

website:
  title: "Market Experiments"
  navbar:
    left:
      - href: regimes.qmd
        text: Home
      - text: Projects
        menu:
          - href: regimes.qmd
          - href: pairs.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-summary: "Show the code"
    self-contained: true
    html-math-method: katex
